### ISSUE TITLE
Fix documentation compilation ModuleNotFoundErrors

### ISSUE THREAD

**Issue by reubano** [concept-to-clinic/concept-to-clinic#164]
## Overview
Currently, when running `docker-compose -f local.yml up compile_docs`, the following errors appear:

```bash
compile_docs_1   | /app/docs/apidoc_interface/backend.api.rst:7: WARNING: toctree contains reference to nonexisting document 'apidoc_interface/backend.api.migrations'
compile_docs_1   | /app/interface/backend/api/serializers.py:docstring of backend.api.serializers.DicomMetadataSerializer:4: ERROR: Unexpected indentation.
compile_docs_1   | /app/interface/backend/api/serializers.py:docstring of backend.api.serializers.DicomMetadataSerializer:7: ERROR: Unexpected indentation.
compile_docs_1   | /app/interface/backend/api/serializers.py:docstring of backend.api.serializers.DicomMetadataSerializer:10: WARNING: Block quote ends without a blank line; unexpected unindent.
compile_docs_1   | /app/interface/backend/api/serializers.py:docstring of backend.api.serializers.DicomMetadataSerializer:13: WARNING: Definition list ends without a blank line; unexpected unindent.
compile_docs_1   | /app/interface/backend/api/serializers.py:docstring of backend.api.serializers.DicomMetadataSerializer:15: WARNING: Block quote ends without a blank line; unexpected unindent.
compile_docs_1   | /app/docs/apidoc_interface/backend.static.rst:10: WARNING: autodoc: failed to import module 'backend.static'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'backend.static'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.rst:17: WARNING: autodoc: failed to import module 'prediction.config'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.rst:26: WARNING: autodoc: failed to import module 'prediction'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.rst:19: WARNING: autodoc: failed to import module 'prediction.src.factory'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.rst:27: WARNING: autodoc: failed to import module 'prediction.src.views'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.rst:36: WARNING: autodoc: failed to import module 'prediction.src'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.rst:16: WARNING: autodoc: failed to import module 'prediction.src.algorithms'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.classify.rst:17: WARNING: autodoc: failed to import module 'prediction.src.algorithms.classify.trained_model'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.classify.rst:26: WARNING: autodoc: failed to import module 'prediction.src.algorithms.classify'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.classify.src.rst:10: WARNING: autodoc: failed to import module 'prediction.src.algorithms.classify.src.gtr123_model'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.classify.src.rst:18: WARNING: autodoc: failed to import module 'prediction.src.algorithms.classify.src.preprocess_patch'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.classify.src.rst:27: WARNING: autodoc: failed to import module 'prediction.src.algorithms.classify.src'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.identify.rst:17: WARNING: autodoc: failed to import module 'prediction.src.algorithms.identify.helpers'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.identify.rst:25: WARNING: autodoc: failed to import module 'prediction.src.algorithms.identify.prediction'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.identify.rst:33: WARNING: autodoc: failed to import module 'prediction.src.algorithms.identify.trained_model'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.identify.rst:42: WARNING: autodoc: failed to import module 'prediction.src.algorithms.identify'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.identify.src.rst:10: WARNING: autodoc: failed to import module 'prediction.src.algorithms.identify.src.gtr123_model'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.identify.src.rst:19: WARNING: autodoc: failed to import module 'prediction.src.algorithms.identify.src'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.segment.rst:10: WARNING: autodoc: failed to import module 'prediction.src.algorithms.segment.trained_model'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.algorithms.segment.rst:19: WARNING: autodoc: failed to import module 'prediction.src.algorithms.segment'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.preprocess.rst:10: WARNING: autodoc: failed to import module 'prediction.src.preprocess.crop_dicom'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.preprocess.rst:18: WARNING: autodoc: failed to import module 'prediction.src.preprocess.crop_patches'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.preprocess.rst:26: WARNING: autodoc: failed to import module 'prediction.src.preprocess.errors'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.preprocess.rst:34: WARNING: autodoc: failed to import module 'prediction.src.preprocess.extract_lungs'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.preprocess.rst:42: WARNING: autodoc: failed to import module 'prediction.src.preprocess.generators'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.preprocess.rst:50: WARNING: autodoc: failed to import module 'prediction.src.preprocess.gtr123_preprocess'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.preprocess.rst:58: WARNING: autodoc: failed to import module 'prediction.src.preprocess.load_ct'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.preprocess.rst:66: WARNING: autodoc: failed to import module 'prediction.src.preprocess.load_dicom'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.preprocess.rst:74: WARNING: autodoc: failed to import module 'prediction.src.preprocess.lung_segmentation'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.preprocess.rst:82: WARNING: autodoc: failed to import module 'prediction.src.preprocess.preprocess_ct'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.preprocess.rst:91: WARNING: autodoc: failed to import module 'prediction.src.preprocess'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:10: WARNING: autodoc: failed to import module 'prediction.src.tests.test_calculate_volume'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:18: WARNING: autodoc: failed to import module 'prediction.src.tests.test_classify_trained_model_predict'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:26: WARNING: autodoc: failed to import module 'prediction.src.tests.test_crop_dicom'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:34: WARNING: autodoc: failed to import module 'prediction.src.tests.test_crop_patches'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:42: WARNING: autodoc: failed to import module 'prediction.src.tests.test_endpoints'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:50: WARNING: autodoc: failed to import module 'prediction.src.tests.test_generators'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:58: WARNING: autodoc: failed to import module 'prediction.src.tests.test_identify_trained_model_predict'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:66: WARNING: autodoc: failed to import module 'prediction.src.tests.test_load_ct'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:74: WARNING: autodoc: failed to import module 'prediction.src.tests.test_load_dicom'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:82: WARNING: autodoc: failed to import module 'prediction.src.tests.test_lung_segmentation'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:90: WARNING: autodoc: failed to import module 'prediction.src.tests.test_preprocess_dicom'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:98: WARNING: autodoc: failed to import module 'prediction.src.tests.test_segment_evaluate'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/prediction.src.tests.rst:107: WARNING: autodoc: failed to import module 'prediction.src.tests'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   | ModuleNotFoundError: No module named 'prediction'
compile_docs_1   | /app/docs/apidoc_prediction/src.rst:19: WARNING: autodoc: failed to import module 'src.factory'; the following exception was raised:
compile_docs_1   | Traceback (most recent call last):
compile_docs_1   |   File "/usr/local/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 547, in import_object
compile_docs_1   |     __import__(self.modname)
compile_docs_1   |   File "/app/prediction/src/factory.py", line 46, in <module>
compile_docs_1   |     app = create_app()
compile_docs_1   |   File "/app/prediction/src/factory.py", line 39, in create_app
compile_docs_1   |     app.config.from_object(getattr(config, config_mode))
compile_docs_1   | AttributeError: module 'config' has no attribute 'Production'
compile_docs_1   | /app/prediction/src/views.py:docstring of src.views.predict:17: WARNING: Definition list ends without a blank line; unexpected unindent.
compile_docs_1   | looking for now-outdated files... none found
compile_docs_1   | pickling environment... done
compile_docs_1   | checking consistency... /app/docs/algorithm_DL_Munich.md:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/algorithm_aidence.md:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/algorithm_alex_andre_gilberto_shize.md:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/algorithm_de_wit.md:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/algorithm_deep_breath.md:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/algorithm_grt123.md:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/algorithm_hammack.md:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/algorithm_mdai.md:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/algorithm_owkin.md:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/algorithm_therapixel.md:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/apidoc_interface/backend.static.rst:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/apidoc_prediction/config.rst:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/apidoc_prediction/src.rst:: WARNING: document isn't included in any toctree
compile_docs_1   | /app/docs/configure git-lfs.md:: WARNING: document isn't included in any toctree
compile_docs_1   | done
compile_docs_1   | /app/docs/templates/algorithm_doc_template.md:: WARNING: document isn't included in any toctree
compile_docs_1   | preparing documents... done
compile_docs_1   | writing output... [  6%] apidoc_interface/backend
compile_docs_1   | writing output... [ 12%] apidoc_interface/backend.api
compile_docs_1   | writing output... [ 18%] apidoc_interface/backend.static
compile_docs_1   | writing output... [ 25%] apidoc_prediction/modules
compile_docs_1   | writing output... [ 31%] apidoc_prediction/prediction
compile_docs_1   | writing output... [ 37%] apidoc_prediction/prediction.src
compile_docs_1   | writing output... [ 43%] apidoc_prediction/prediction.src.algorithms
compile_docs_1   | writing output... [ 50%] apidoc_prediction/prediction.src.algorithms.classify
compile_docs_1   | writing output... [ 56%] apidoc_prediction/prediction.src.algorithms.classify.src
compile_docs_1   | writing output... [ 62%] apidoc_prediction/prediction.src.algorithms.identify
compile_docs_1   | writing output... [ 68%] apidoc_prediction/prediction.src.algorithms.identify.src
compile_docs_1   | writing output... [ 75%] apidoc_prediction/prediction.src.algorithms.segment
compile_docs_1   | writing output... [ 81%] apidoc_prediction/prediction.src.preprocess
compile_docs_1   | writing output... [ 87%] apidoc_prediction/prediction.src.tests
compile_docs_1   | writing output... [ 93%] apidoc_prediction/src
compile_docs_1   | writing output... [100%] index
compile_docs_1   | 
compile_docs_1   | generating indices... genindex py-modindex
compile_docs_1   | writing additional pages... search
compile_docs_1   | copying static files... done
compile_docs_1   | copying extra files... done
compile_docs_1   | dumping search index in English (code: en) ... done
compile_docs_1   | dumping object inventory... done
compile_docs_1   | build succeeded, 67 warnings.
compile_docs_1   | 
compile_docs_1   | Build finished. The HTML pages are in _build/html.
compile_docs_1   | Sphinx build finished. The build files are in _build/
compile_docs_1   | make: Leaving directory '/app/docs'
```

CR #90 

## Expected Behavior

The `ModuleNotFoundError`s should not occur

## Steps to Reproduce

1. Update master `git pull`
2. Rebuild and run the `compile_docs` container with `docker-compose -f local.yml up --build compile_docs`

## Acceptance criteria

 - [ ] running `docker-compose -f local.yml up compile_docs` should not produce the above errors 

*NOTE: All PRs must follow the standard PR checklist.*

**Comment by lamby** [comment]
Merged - thanks!
