### ISSUE TITLE
Cannot build from docker

### ISSUE THREAD

**Issue by louisgv** [concept-to-clinic/concept-to-clinic#287]
I pulled from latest and tried to clean and rebuild docker. However, it failed on my system.

## Expected Behavior

Running `docker-compose -f local.yml build` should build the application.

## Current Behavior

The following error was thrown:
```
  Running setup.py clean for networkx
Successfully built sqlalchemy
Failed to build networkx
Installing collected packages: pyflakes, pycodestyle, mccabe, flake8, py, pytest, scipy, cycler, pyparsing, matplotlib, decorator, networkx, PyWavelets, scikit-image, sqlalchemy, pylidc
  Running setup.py install for networkx: started
    Running setup.py install for networkx: finished with status 'done'
Successfully installed PyWavelets-0.5.2 cycler-0.10.0 decorator-4.2.1 flake8-3.3.0 matplotlib-2.1.1 mccabe-0.6.1 networkx-2.0 py-1.5.2 pycodestyle-2.3.1 pyflakes-1.5.0 pylidc-0.1.9 pyparsing-2.2.0 pytest-3.1.3 scikit-image-0.13.1 scipy-1.0.0 sqlalchemy-1.2.1
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'options'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/commands/install.py", line 385, in run
    requirement_set.cleanup_files()
  File "/usr/local/lib/python3.6/dist-packages/pip/utils/build.py", line 38, in __exit__
    self.cleanup()
  File "/usr/local/lib/python3.6/dist-packages/pip/utils/build.py", line 42, in cleanup
    rmtree(self.name)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.6/dist-packages/pip/utils/__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 418, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/pip/utils/__init__.py", line 114, in rmtree_errorhandler
    func(path)
IsADirectoryError: [Errno 21] Is a directory: '/tmp/pip-build-hv_u296y/flake8/flake8/options'
ERROR: Service 'base' failed to build: The command '/bin/sh -c pip install -r /requirements/prediction/local.txt' returned a non-zero code: 2

```

## Steps to Reproduce

1. Pull from master
2. Run `docker-compose -f local.yml build`

## Context (Environment)

+ Linux Debian
+ Docker version 17.09.0-ce, build afdb6d4
+ docker-compose version 1.17.0, build ac53b73

## Checklist before submitting
- [x] I have confirmed this using the officially supported Docker Compose setup using the `local.yml` configuration and ensured that I built the containers again and they reflect the most recent version of the project at the `HEAD` commit on the `master` branch 
- [x] I have searched through the other currently open issues and am confident this is not a duplicate of an existing bug
- [x] I provided a **minimal code snippet** or list of steps that reproduces the bug.
- [ ] I provided **screenshots** where appropriate
- [x] I filled out all the relevant sections of this template

**Comment by WGierke** [comment]
Unfortunately, I can't confirm that on
- Linux Ubuntu 16.04.3 LTS
- Docker version 17.09.0-ce, build afdb6d4
- docker-compose version 1.15.0, build e12f3b9

**Comment by louisgv** [comment]
Hmm, this error was thrown only if I tried to run docker integrated with my external drive. If I disable the external drive and run docker, it seems to be running now...

**Comment by reubano** [comment]
Yes, I had issues before using an external drive as well. Also, see #165 for potential solutions to the space issue.
